import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.4";
import { Resend } from "https://esm.sh/resend@2.0.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Company details - PROCURESAATHI SOLUTIONS PRIVATE LIMITED
const COMPANY_DETAILS = {
  name: "PROCURESAATHI SOLUTIONS PRIVATE LIMITED",
  address: "METRO PILLAR NUMBER 564, 14/3 MATHURA ROAD, SECTOR 31, FARIDABAD, Haryana - 121003",
  gstin: "06AAMCP4662L1ZW",
  pan: "AAMCP4662L",
  state: "Haryana",
  stateCode: "06",
  email: "accounts@procuresaathi.com",
  phone: "+91 8368127357",
  bankName: "HDFC Bank",
  bankAccount: "50200089456523",
  bankIfsc: "HDFC0001234",
  bankBranch: "Faridabad Sector 31",
};

interface InvoiceRequest {
  payment_type: "email_subscription" | "premium_pack";
  payment_id: string; // order_id from payment
  user_id: string;
  amount: number;
  tax_amount: number;
  total_amount: number;
  description: string;
  customer_name: string;
  customer_email: string;
  customer_phone?: string;
  customer_gstin?: string;
  customer_address?: string;
  customer_state?: string;
  metadata?: Record<string, any>;
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");

    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error("Missing Supabase configuration");
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const resend = RESEND_API_KEY ? new Resend(RESEND_API_KEY) : null;

    const invoiceRequest: InvoiceRequest = await req.json();
    console.log("Generating invoice for:", invoiceRequest);

    // Check if invoice already exists for this payment
    const { data: existingInvoice } = await supabase
      .from("subscription_invoices")
      .select("id, invoice_number")
      .eq("payment_id", invoiceRequest.payment_id)
      .single();

    if (existingInvoice) {
      console.log("Invoice already exists:", existingInvoice.invoice_number);
      return new Response(
        JSON.stringify({ 
          success: true, 
          message: "Invoice already exists",
          invoice_number: existingInvoice.invoice_number 
        }),
        { status: 200, headers: { "Content-Type": "application/json", ...corsHeaders } }
      );
    }

    // Determine if CGST/SGST or IGST based on customer state
    const customerState = invoiceRequest.customer_state?.toLowerCase() || "";
    const isHaryana = customerState.includes("haryana");
    
    const taxAmount = invoiceRequest.tax_amount;
    const cgstAmount = isHaryana ? taxAmount / 2 : 0;
    const sgstAmount = isHaryana ? taxAmount / 2 : 0;
    const igstAmount = isHaryana ? 0 : taxAmount;

    // Calculate base price (before GST)
    const basePrice = invoiceRequest.amount;

    // Determine place of supply
    const placeOfSupply = customerState 
      ? `${customerState.charAt(0).toUpperCase() + customerState.slice(1)}` 
      : "Haryana (06)";

    // Insert invoice record (invoice_number is auto-generated by trigger)
    const { data: invoice, error: invoiceError } = await supabase
      .from("subscription_invoices")
      .insert({
        user_id: invoiceRequest.user_id,
        payment_type: invoiceRequest.payment_type,
        payment_id: invoiceRequest.payment_id,
        customer_name: invoiceRequest.customer_name,
        customer_email: invoiceRequest.customer_email,
        customer_phone: invoiceRequest.customer_phone,
        customer_address: invoiceRequest.customer_address,
        customer_gstin: invoiceRequest.customer_gstin,
        description: invoiceRequest.description,
        hsn_sac_code: "998314", // SAC code for online marketplace services
        quantity: 1,
        unit_price: basePrice,
        tax_rate: 18,
        cgst_amount: cgstAmount,
        sgst_amount: sgstAmount,
        igst_amount: igstAmount,
        subtotal: basePrice,
        total_tax: taxAmount,
        total_amount: invoiceRequest.total_amount,
        place_of_supply: placeOfSupply,
        payment_date: new Date().toISOString(),
      })
      .select()
      .single();

    if (invoiceError) {
      console.error("Error creating invoice:", invoiceError);
      throw new Error("Failed to create invoice record");
    }

    console.log("Invoice created:", invoice.invoice_number);

    // Generate email HTML
    const invoiceHtml = generateInvoiceEmailHtml(invoice, isHaryana);

    // Send email with invoice
    if (resend && invoiceRequest.customer_email) {
      try {
        const emailResponse = await resend.emails.send({
          from: "ProcureSaathi <accounts@procuresaathi.com>",
          to: [invoiceRequest.customer_email],
          subject: `Tax Invoice ${invoice.invoice_number} - ProcureSaathi`,
          html: invoiceHtml,
        });

        console.log("Invoice email sent:", emailResponse);

        // Update invoice with email sent status
        await supabase
          .from("subscription_invoices")
          .update({ 
            email_sent: true, 
            email_sent_at: new Date().toISOString() 
          })
          .eq("id", invoice.id);
      } catch (emailError) {
        console.error("Error sending invoice email:", emailError);
        // Don't throw - invoice was created, email failed
      }
    }

    return new Response(
      JSON.stringify({ 
        success: true, 
        invoice_number: invoice.invoice_number,
        invoice_id: invoice.id 
      }),
      { status: 200, headers: { "Content-Type": "application/json", ...corsHeaders } }
    );

  } catch (error: any) {
    console.error("Invoice generation error:", error);
    return new Response(
      JSON.stringify({ success: false, error: error.message }),
      { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
    );
  }
});

function generateInvoiceEmailHtml(invoice: any, isHaryana: boolean): string {
  const formatCurrency = (amount: number) => 
    `₹${amount.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  
  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-IN', { 
      day: '2-digit', 
      month: '2-digit', 
      year: 'numeric' 
    });
  };

  const taxRows = isHaryana 
    ? `
      <tr>
        <td style="padding: 8px; border-bottom: 1px solid #eee;">CGST @ 9%</td>
        <td style="padding: 8px; border-bottom: 1px solid #eee; text-align: right;">${formatCurrency(invoice.cgst_amount)}</td>
      </tr>
      <tr>
        <td style="padding: 8px; border-bottom: 1px solid #eee;">SGST @ 9%</td>
        <td style="padding: 8px; border-bottom: 1px solid #eee; text-align: right;">${formatCurrency(invoice.sgst_amount)}</td>
      </tr>
    `
    : `
      <tr>
        <td style="padding: 8px; border-bottom: 1px solid #eee;">IGST @ 18%</td>
        <td style="padding: 8px; border-bottom: 1px solid #eee; text-align: right;">${formatCurrency(invoice.igst_amount)}</td>
      </tr>
    `;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Tax Invoice - ${invoice.invoice_number}</title>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 20px; }
    .invoice-container { max-width: 800px; margin: 0 auto; border: 1px solid #ddd; padding: 30px; }
    .header { text-align: center; border-bottom: 2px solid #0066cc; padding-bottom: 20px; margin-bottom: 20px; }
    .company-name { font-size: 24px; font-weight: bold; color: #0066cc; margin-bottom: 5px; }
    .invoice-title { font-size: 20px; font-weight: bold; color: #333; margin: 15px 0; }
    .section { margin-bottom: 20px; }
    .section-title { font-weight: bold; color: #0066cc; border-bottom: 1px solid #0066cc; padding-bottom: 5px; margin-bottom: 10px; }
    .details-grid { display: flex; justify-content: space-between; flex-wrap: wrap; }
    .details-column { width: 48%; }
    .label { color: #666; font-size: 12px; }
    .value { font-weight: 500; margin-bottom: 8px; }
    table { width: 100%; border-collapse: collapse; margin: 15px 0; }
    th { background-color: #0066cc; color: white; padding: 10px; text-align: left; }
    td { padding: 10px; border-bottom: 1px solid #eee; }
    .totals-table { width: 300px; margin-left: auto; }
    .totals-table td { padding: 8px; }
    .grand-total { font-size: 18px; font-weight: bold; color: #0066cc; }
    .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
    .bank-details { background: #f9f9f9; padding: 15px; border-radius: 5px; margin-top: 20px; }
  </style>
</head>
<body>
  <div class="invoice-container">
    <div class="header">
      <div class="company-name">${COMPANY_DETAILS.name}</div>
      <div style="font-size: 12px; color: #666;">
        ${COMPANY_DETAILS.address}<br>
        GSTIN: ${COMPANY_DETAILS.gstin} | PAN: ${COMPANY_DETAILS.pan}<br>
        Email: ${COMPANY_DETAILS.email} | Phone: ${COMPANY_DETAILS.phone}
      </div>
      <div class="invoice-title">TAX INVOICE</div>
    </div>

    <div class="details-grid">
      <div class="details-column">
        <div class="section-title">Invoice Details</div>
        <div class="label">Invoice Number</div>
        <div class="value">${invoice.invoice_number}</div>
        <div class="label">Invoice Date</div>
        <div class="value">${formatDate(invoice.invoice_date)}</div>
        <div class="label">Place of Supply</div>
        <div class="value">${invoice.place_of_supply}</div>
      </div>
      <div class="details-column">
        <div class="section-title">Bill To</div>
        <div class="value" style="font-weight: bold;">${invoice.customer_name}</div>
        ${invoice.customer_address ? `<div class="value">${invoice.customer_address}</div>` : ''}
        ${invoice.customer_gstin ? `<div class="label">GSTIN: <span class="value">${invoice.customer_gstin}</span></div>` : ''}
        ${invoice.customer_email ? `<div class="label">Email: <span class="value">${invoice.customer_email}</span></div>` : ''}
        ${invoice.customer_phone ? `<div class="label">Phone: <span class="value">${invoice.customer_phone}</span></div>` : ''}
      </div>
    </div>

    <table>
      <thead>
        <tr>
          <th style="width: 5%;">#</th>
          <th style="width: 45%;">Description</th>
          <th style="width: 15%;">SAC Code</th>
          <th style="width: 10%;">Qty</th>
          <th style="width: 15%;">Rate</th>
          <th style="width: 15%;">Amount</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1</td>
          <td>${invoice.description}</td>
          <td>${invoice.hsn_sac_code}</td>
          <td>${invoice.quantity}</td>
          <td style="text-align: right;">${formatCurrency(invoice.unit_price)}</td>
          <td style="text-align: right;">${formatCurrency(invoice.subtotal)}</td>
        </tr>
      </tbody>
    </table>

    <table class="totals-table">
      <tr>
        <td>Subtotal</td>
        <td style="text-align: right;">${formatCurrency(invoice.subtotal)}</td>
      </tr>
      ${taxRows}
      <tr style="border-top: 2px solid #0066cc;">
        <td class="grand-total">Total</td>
        <td class="grand-total" style="text-align: right;">${formatCurrency(invoice.total_amount)}</td>
      </tr>
    </table>

    <div class="bank-details">
      <div class="section-title">Bank Details for Payment</div>
      <div><strong>Bank Name:</strong> ${COMPANY_DETAILS.bankName}</div>
      <div><strong>Account Number:</strong> ${COMPANY_DETAILS.bankAccount}</div>
      <div><strong>IFSC Code:</strong> ${COMPANY_DETAILS.bankIfsc}</div>
      <div><strong>Branch:</strong> ${COMPANY_DETAILS.bankBranch}</div>
    </div>

    <div class="footer">
      <p><strong>Terms & Conditions:</strong></p>
      <ol style="margin: 5px 0; padding-left: 20px;">
        <li>This is a computer-generated invoice and does not require a signature.</li>
        <li>Payment is non-refundable once the service is activated.</li>
        <li>Subject to Faridabad jurisdiction only.</li>
      </ol>
      <p style="text-align: center; margin-top: 20px;">
        <strong>Thank you for your business!</strong><br>
        For any queries, please contact ${COMPANY_DETAILS.email}
      </p>
    </div>
  </div>
</body>
</html>
  `;
}
